spring.application.name=TransactionX

## jsp
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

#db connection(Oracle)
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/orcl
spring.datasource.username=study
spring.datasource.password=1234

server.port=8081

#Mybatis
mybatis.mapper-locations=classpath:mybatis/mapper/**/**.xml